# Book settings
title: Introduction to Python for Humanists
author: William J.B. Mattingly
logo: 'images/crc-press-logo.jpg'
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true
# Information about where the book exists on the web
repository:
  url: https://github.com/wjbmattingly/python_for_dh # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false